In [1]:
#Importing Libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
!pip install mlflow

Requirement already satisfied: mlflow in /home/codespace/anaconda3/lib/python3.9/site-packages (3.1.4)
Requirement already satisfied: gunicorn<24 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (23.0.0)
Requirement already satisfied: matplotlib<4 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (3.5.1)
Requirement already satisfied: mlflow-skinny==3.1.4 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (3.1.4)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.4.32)
Requirement already satisfied: Flask<4 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.1.2)
Requirement already satisfied: pandas<3 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.4.2)
Requirement already satisfied: graphene<4 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (3.4.3)
Requirement already satisfied: scikit-learn<2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.0.2)
Requirement already satisfied: scipy<2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.7.3)
Requirement already satisfied: alembic!=1.10.0,<2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.16.5)
Requirement already satisfied: pyarrow<21,>=4.0.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (20.0.0)
Requirement already satisfied: numpy<3 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.21.5)
Requirement already satisfied: docker<8,>=4.0.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (7.1.0)
Requirement already satisfied: protobuf<7,>=3.12.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (6.33.6)
Requirement already satisfied: gitpython<4,>=3.1.9 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (3.1.50)
Requirement already satisfied: fastapi<1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (0.128.8)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (4.15.0)
Requirement already satisfied: pydantic<3,>=1.10.8 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (2.13.4)
Requirement already satisfied: uvicorn<1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (0.39.0)
Requirement already satisfied: requests<3,>=2.17.3 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (2.32.5)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (0.5.5)
Requirement already satisfied: cachetools<7,>=5.0.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (8.0.4)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (1.41.1)
Requirement already satisfied: pyyaml<7,>=5.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (6.0)
Requirement already satisfied: cloudpickle<4 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (2.0.0)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (0.102.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (1.41.1)
Requirement already satisfied: packaging<26 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (21.3)
Requirement already satisfied: Mako in /home/codespace/anaconda3/lib/python3.9/site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.12)
Requirement already satisfied: tomli in /home/codespace/anaconda3/lib/python3.9/site-packages (from alembic!=1.10.0,<2->mlflow) (1.2.2)
Requirement already satisfied: google-auth~=2.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.4->mlflow) (2.50.0)
Requirement already satisfied: urllib3>=1.26.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from docker<8,>=4.0.0->mlflow) (1.26.9)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from fastapi<1->mlflow-skinny==3.1.4->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from fastapi<1->mlflow-skinny==3.1.4->mlflow) (0.0.4)
Requirement already satisfied: starlette<1.0.0,>=0.40.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from fastapi<1->mlflow-skinny==3.1.4->mlflow) (0.49.3)
Requirement already satisfied: Jinja2>=2.10.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from Flask<4->mlflow) (2.11.3)
Requirement already satisfied: itsdangerous>=0.24 in /home/codespace/anaconda3/lib/python3.9/site-packages (from Flask<4->mlflow) (2.0.1)
Requirement already satisfied: Werkzeug>=0.15 in /home/codespace/anaconda3/lib/python3.9/site-packages (from Flask<4->mlflow) (2.0.3)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.1.4->mlflow) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.1.4->mlflow) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.4->mlflow) (0.2.8)
Requirement already satisfied: cryptography>=38.0.3 in /home/codespace/anaconda3/lib/python3.9/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.4->mlflow) (48.0.0)
Requirement already satisfied: cffi>=2.0.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from cryptography>=38.0.3->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.4->mlflow) (2.0.0)
Requirement already satisfied: pycparser in /home/codespace/anaconda3/lib/python3.9/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.4->mlflow) (2.21)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from graphene<4->mlflow) (2.8.2)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from graphene<4->mlflow) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: zipp>=3.20 in /home/codespace/anaconda3/lib/python3.9/site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.1.4->mlflow) (3.23.1)
Requirement already satisfied: MarkupSafe>=0.23 in /home/codespace/anaconda3/lib/python3.9/site-packages (from Jinja2>=2.10.1->Flask<4->mlflow) (2.0.1)
Requirement already satisfied: pyparsing>=2.2.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from matplotlib<4->mlflow) (3.0.4)
Requirement already satisfied: cycler>=0.10 in /home/codespace/anaconda3/lib/python3.9/site-packages (from matplotlib<4->mlflow) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from matplotlib<4->mlflow) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from matplotlib<4->mlflow) (4.25.0)
Requirement already satisfied: pillow>=6.2.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from matplotlib<4->mlflow) (9.0.1)

Requirement already satisfied: opentelemetry-semantic-conventions==0.62b1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.1.4->mlflow) (0.62b1)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from pandas<3->mlflow) (2021.3)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/codespace/anaconda3/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.4->mlflow) (0.4.8)
Requirement already satisfied: pydantic-core==2.46.4 in /home/codespace/anaconda3/lib/python3.9/site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.1.4->mlflow) (2.46.4)
Requirement already satisfied: annotated-types>=0.6.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.1.4->mlflow) (0.7.0)
Requirement already satisfied: six>=1.5 in /home/codespace/anaconda3/lib/python3.9/site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/anaconda3/lib/python3.9/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.4->mlflow) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/anaconda3/lib/python3.9/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.4->mlflow) (3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.4->mlflow) (2.0.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from scikit-learn<2->mlflow) (2.2.0)
Requirement already satisfied: joblib>=0.11 in /home/codespace/anaconda3/lib/python3.9/site-packages (from scikit-learn<2->mlflow) (1.1.0)
Requirement already satisfied: greenlet!=0.4.17 in /home/codespace/anaconda3/lib/python3.9/site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (1.1.1)
Requirement already satisfied: anyio<5,>=3.6.2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from starlette<1.0.0,>=0.40.0->fastapi<1->mlflow-skinny==3.1.4->mlflow) (4.12.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from anyio<5,>=3.6.2->starlette<1.0.0,>=0.40.0->fastapi<1->mlflow-skinny==3.1.4->mlflow) (1.3.1)
Requirement already satisfied: h11>=0.8 in /home/codespace/anaconda3/lib/python3.9/site-packages (from uvicorn<1->mlflow-skinny==3.1.4->mlflow) (0.16.0)

In [3]:
import mlflow

In [4]:
mlflow.set_tracking_uri("sqlite:///mlflow.db")

In [5]:
mlflow.set_experiment("HousePricePrediction")

2026/05/26 08:41:43 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/05/26 08:41:43 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
2026/05/26 08:41:43 INFO mlflow.tracking.fluent: Experiment with name 'HousePricePrediction' does not exist. Creating a new experiment.

In [6]:
data = pd.read_csv('House Price Prediction Dataset.csv')

In [7]:
data.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   object
 7   Condition  2000 non-null   object
 8   Garage     2000 non-null   object
 9   Price      2000 non-null   int64
dtypes: int64(7), object(3)
memory usage: 156.4+ KB

In [9]:
data.describe()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price
count,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000
mean,1000.500000,2786.209500,3.003500,2.55250,1.993500,1961.446000,537676.855000
std,577.494589,1295.146799,1.424606,1.10899,0.809188,35.926695,276428.845719
min,1.000000,501.000000,1.000000,1.00000,1.000000,1900.000000,50005.000000
25%,500.750000,1653.000000,2.000000,2.00000,1.000000,1930.000000,300098.000000
50%,1000.500000,2833.000000,3.000000,3.00000,2.000000,1961.000000,539254.000000
75%,1500.250000,3887.500000,4.000000,4.00000,3.000000,1993.000000,780086.000000
max,2000.000000,4999.000000,5.000000,4.00000,3.000000,2023.000000,999656.000000

In [10]:
data['Location'].unique()

array(['Downtown', 'Suburban', 'Urban', 'Rural'], dtype=object)

In [11]:
data['Condition'].unique()

array(['Excellent', 'Good', 'Fair', 'Poor'], dtype=object)

In [12]:
data['Garage'].unique()

array(['No', 'Yes'], dtype=object)

In [13]:
final_df  = pd.get_dummies(data = data,drop_first=True, columns=['Location', 'Condition', 'Garage'], dtype='int')

In [14]:
final_df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price,Location_Rural,Location_Suburban,Location_Urban,Condition_Fair,Condition_Good,Condition_Poor,Garage_Yes
0,1,1360,5,4,3,1970,149919,0,0,0,0,0,0,0
1,2,4272,5,4,3,1958,424998,0,0,0,0,0,0,0
2,3,3592,2,2,3,1938,266746,0,0,0,0,1,0,0
3,4,966,4,2,2,1902,244020,0,1,0,1,0,0,1
4,5,4926,1,4,2,1975,636056,0,0,0,1,0,0,1

In [15]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score

In [16]:
features = final_df[final_df.columns.drop(['Id','Price', 'YearBuilt'])].values

In [17]:
target = final_df['Price'].values

In [18]:
features

array([[1360,    5,    4, ...,    0,    0,    0],
       [4272,    5,    4, ...,    0,    0,    0],
       [3592,    2,    2, ...,    1,    0,    0],
       ...,
       [1062,    5,    1, ...,    0,    1,    0],
       [4062,    3,    1, ...,    0,    0,    1],
       [2989,    5,    1, ...,    0,    0,    0]])

In [19]:
target

array([149919, 424998, 266746, ..., 476925, 161119, 482525])

In [20]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.20, random_state=42)

In [21]:
training_data_path = final_df.to_csv('cleaned_data.csv')

# Running Different Models

In [22]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [23]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [24]:
##  Multiple Linear Regression

In [25]:
with mlflow.start_run():
    mlflow.set_tag("developer", "Praveen")
    mlflow.log_param("data", "/workspaces/mlops_sample/cleaned_data.csv")
    linear_reg = LinearRegression()
    linear_reg.fit(X_train, y_train)
    y_prediction = linear_reg.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))
    r2_score = r2_score(y_true=y_test, y_pred=y_prediction)
    mlflow.log_metric("rmse", rmse)
    mlflow.log_metric("r2_score", r2_score)

In [26]:
with mlflow.start_run(run_name="Polynomial Regression"):
    mlflow.set_tag("developer", "Praveen")
    mlflow.log_param("data", "/workspaces/mlops_sample/cleaned_data.csv")
    mlflow.log_param("algorithm", "Polynomial Function")
    mlflow.log_param("polynomial_degree", "4")
    poly = PolynomialFeatures(degree=4, include_bias=False)
    X_poly = poly.fit_transform(X_train)
    model = LinearRegression()
    model.fit(X_poly, y_train)
    y_prediction = model.predict(poly.fit_transform(X_test))
    rmse = np.sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))
    mlflow.log_metric("rmse", rmse)

In [27]:
!pip install xgboost

Requirement already satisfied: xgboost in /home/codespace/anaconda3/lib/python3.9/site-packages (2.1.4)
Requirement already satisfied: scipy in /home/codespace/anaconda3/lib/python3.9/site-packages (from xgboost) (1.7.3)
Requirement already satisfied: numpy in /home/codespace/anaconda3/lib/python3.9/site-packages (from xgboost) (1.21.5)
Requirement already satisfied: nvidia-nccl-cu12 in /home/codespace/anaconda3/lib/python3.9/site-packages (from xgboost) (2.30.4)

In [28]:
from xgboost import XGBRegressor

In [29]:
xgb = XGBRegressor()

In [30]:
with mlflow.start_run(run_name="XGB Regressor default"):
    mlflow.set_tag("developer", "Praveen")
    mlflow.log_param("algorithm", "XGB Regressor with default Params")
    mlflow.log_param("data", "/workspaces/mlops_sample/cleaned_data.csv")
    xgb.fit(X_train, y_train)
    y_prediction = xgb.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))
    mlflow.log_metric("rmse", rmse)

In [34]:
!pip install hyperopt

Collecting hyperopt
  Downloading hyperopt-0.2.7-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 12.8 MB/s eta 0:00:01
Collecting py4j
  Downloading py4j-0.10.9.9-py2.py3-none-any.whl (203 kB)
     |████████████████████████████████| 203 kB 80.7 MB/s eta 0:00:01
Requirement already satisfied: future in /home/codespace/anaconda3/lib/python3.9/site-packages (from hyperopt) (0.18.2)
Requirement already satisfied: networkx>=2.2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from hyperopt) (2.7.1)
Requirement already satisfied: numpy in /home/codespace/anaconda3/lib/python3.9/site-packages (from hyperopt) (1.21.5)
Requirement already satisfied: six in /home/codespace/anaconda3/lib/python3.9/site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: cloudpickle in /home/codespace/anaconda3/lib/python3.9/site-packages (from hyperopt) (2.0.0)
Requirement already satisfied: tqdm in /home/codespace/anaconda3/lib/python3.9/site-packages (from hyperopt) (4.64.0)
Requirement already satisfied: scipy in /home/codespace/anaconda3/lib/python3.9/site-packages (from hyperopt) (1.7.3)
Installing collected packages: py4j, hyperopt
Successfully installed hyperopt-0.2.7 py4j-0.10.9.9

In [35]:
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials

In [38]:
k = 5
print(f'thenumber is {k}')

thenumber is 5

In [36]:
import xgboost as xgb

In [41]:
# 1. Define the search space
space = {
    'max_depth': hp.quniform('max_depth', 3, 10, 1),
    'learning_rate': hp.loguniform('learning_rate', -3, 0),
    'n_estimators': hp.quniform('n_estimators', 100, 1000, 10),
    'reg_alpha': hp.uniform('reg_alpha', 0, 1),
    'reg_lambda': hp.uniform('reg_lambda', 0, 1)
}


# 2. Define the objective function

def objective(params):
    # Convert parameters to correct types (Hyperopt often returns floats)
    params['max_depth'] = int(params['max_depth'])
    params['n_estimators'] = int(params['n_estimators'])
    
    with mlflow.start_run(nested=True):
        mlflow.set_tag("model", "xgboost")
        model = xgb.XGBRegressor(**params, early_stopping_rounds=10, random_state=42)
        model.fit(X_train, y_train, eval_set=[(X_test, y_test)])
        preds = model.predict(X_test)
        rmse = mean_squared_error(y_test, preds, squared=False)
        actual_trees = model.best_iteration if hasattr(model, 'best_iteration') else params['n_estimators']

# Log to MLflow
        mlflow.log_params(params)
        mlflow.log_metric("rmse", rmse)
        mlflow.log_metric("best_iteration", actual_trees)
        
        return {'loss': rmse, 'status': STATUS_OK}


with mlflow.start_run(run_name="XGB_Hyperopt_Optimization"):
    best_params = fmin(fn = objective, space = space, algo = tpe.suggest, max_evals = 50, trials = Trials())
    mlflow.log_params(best_params)

[0]	validation_0-rmse:282212.39253
[1]	validation_0-rmse:283091.62061
[2]	validation_0-rmse:283589.50348
[3]	validation_0-rmse:285447.53838
[4]	validation_0-rmse:285923.36144
[5]	validation_0-rmse:286095.05519
[6]	validation_0-rmse:288719.90786
[7]	validation_0-rmse:291126.70455
[8]	validation_0-rmse:293188.10842
[9]	validation_0-rmse:292519.12472
[10]	validation_0-rmse:295225.67913
[0]	validation_0-rmse:282316.42664
[1]	validation_0-rmse:285112.59405
[2]	validation_0-rmse:287480.62590
[3]	validation_0-rmse:287880.97933
[4]	validation_0-rmse:289799.84812
[5]	validation_0-rmse:290755.35041
[6]	validation_0-rmse:292430.31730
[7]	validation_0-rmse:293651.11495
[8]	validation_0-rmse:294280.90314
[9]	validation_0-rmse:296511.96067
[10]	validation_0-rmse:298080.00904
[0]	validation_0-rmse:284810.38388
[1]	validation_0-rmse:289090.03321
[2]	validation_0-rmse:292117.35733
[3]	validation_0-rmse:295670.90817
[4]	validation_0-rmse:299573.30690
[5]	validation_0-rmse:302328.33560
[6]	validation_0-rmse:304332.22784
[7]	validation_0-rmse:305560.11236
[8]	validation_0-rmse:306864.31319
[9]	validation_0-rmse:308508.23834
[0]	validation_0-rmse:280949.62805
[1]	validation_0-rmse:283717.92448
[2]	validation_0-rmse:284703.02786
[3]	validation_0-rmse:286981.97904
[4]	validation_0-rmse:290172.64462
[5]	validation_0-rmse:289835.29743
[6]	validation_0-rmse:292376.53867
[7]	validation_0-rmse:293730.66316
[8]	validation_0-rmse:294148.96909
[9]	validation_0-rmse:294716.93153
[10]	validation_0-rmse:295138.75561
[0]	validation_0-rmse:282306.40483
[1]	validation_0-rmse:287036.28764
[2]	validation_0-rmse:285431.64809
[3]	validation_0-rmse:288377.25024
[4]	validation_0-rmse:287315.08458
[5]	validation_0-rmse:288988.09912
[6]	validation_0-rmse:292211.37836
[7]	validation_0-rmse:293711.72616
[8]	validation_0-rmse:293736.32644
[9]	validation_0-rmse:294344.53506
[0]	validation_0-rmse:280072.01064
[1]	validation_0-rmse:280743.98944
[2]	validation_0-rmse:281172.92914
[3]	validation_0-rmse:281175.11003
[4]	validation_0-rmse:281829.07951
[5]	validation_0-rmse:282241.21964
[6]	validation_0-rmse:282459.02400
[7]	validation_0-rmse:282710.82973
[8]	validation_0-rmse:283063.46940
[9]	validation_0-rmse:282951.67100
[10]	validation_0-rmse:282729.54618
[0]	validation_0-rmse:279731.17150
[1]	validation_0-rmse:280355.25914

[2]	validation_0-rmse:282111.34803
[3]	validation_0-rmse:282430.82342
[4]	validation_0-rmse:284363.26810
[5]	validation_0-rmse:285414.37229
[6]	validation_0-rmse:286288.93840
[7]	validation_0-rmse:286703.56534
[8]	validation_0-rmse:288122.36662
[9]	validation_0-rmse:288721.75457
[10]	validation_0-rmse:289969.92272
[0]	validation_0-rmse:279793.24359
[1]	validation_0-rmse:281180.45463
[2]	validation_0-rmse:282702.91232
[3]	validation_0-rmse:283362.58501
[4]	validation_0-rmse:283948.63778
[5]	validation_0-rmse:284257.44106
[6]	validation_0-rmse:283423.63017
[7]	validation_0-rmse:283653.50444
[8]	validation_0-rmse:283669.23925
[9]	validation_0-rmse:284302.31339
[10]	validation_0-rmse:285641.41129
[0]	validation_0-rmse:283251.92848
[1]	validation_0-rmse:287546.90062
[2]	validation_0-rmse:290449.02974
[3]	validation_0-rmse:294264.41398
[4]	validation_0-rmse:297368.56469
[5]	validation_0-rmse:300536.89270
[6]	validation_0-rmse:302457.39545
[7]	validation_0-rmse:303643.56071
[8]	validation_0-rmse:304541.13320
[9]	validation_0-rmse:304688.10021
[0]	validation_0-rmse:278961.28810
[1]	validation_0-rmse:279491.80595
[2]	validation_0-rmse:279763.51176
[3]	validation_0-rmse:279996.63648
[4]	validation_0-rmse:280296.23943
[5]	validation_0-rmse:280568.48081
[6]	validation_0-rmse:280375.96371
[7]	validation_0-rmse:280477.04296
[8]	validation_0-rmse:281123.38716
[9]	validation_0-rmse:281141.02943
[0]	validation_0-rmse:278963.64035
[1]	validation_0-rmse:279497.27344
[2]	validation_0-rmse:279770.41404
[3]	validation_0-rmse:280006.68630
[4]	validation_0-rmse:280306.25066
[5]	validation_0-rmse:280583.89266
[6]	validation_0-rmse:280389.17594
[7]	validation_0-rmse:280148.73855
[8]	validation_0-rmse:280795.09848
[9]	validation_0-rmse:280809.01834
[0]	validation_0-rmse:279178.54729
[1]	validation_0-rmse:279458.36441
[2]	validation_0-rmse:279745.19921
[3]	validation_0-rmse:280154.89326
[4]	validation_0-rmse:280604.46886
[5]	validation_0-rmse:281061.54150
[6]	validation_0-rmse:281597.43246
[7]	validation_0-rmse:281744.38595
[8]	validation_0-rmse:281972.64752
[9]	validation_0-rmse:282127.98808
[10]	validation_0-rmse:282293.78681
[0]	validation_0-rmse:279036.38023
[1]	validation_0-rmse:279193.31379
[2]	validation_0-rmse:279394.31601
[3]	validation_0-rmse:279539.51813
[4]	validation_0-rmse:279830.75719

[5]	validation_0-rmse:280211.50652
[6]	validation_0-rmse:280393.86904
[7]	validation_0-rmse:280441.62603
[8]	validation_0-rmse:280653.90536
[9]	validation_0-rmse:280907.10562
[0]	validation_0-rmse:279712.63725
[1]	validation_0-rmse:280178.16651
[2]	validation_0-rmse:280425.32113
[3]	validation_0-rmse:280833.99711
[4]	validation_0-rmse:281010.70057
[5]	validation_0-rmse:281708.49886
[6]	validation_0-rmse:281992.10220
[7]	validation_0-rmse:282205.52023
[8]	validation_0-rmse:282527.22544
[9]	validation_0-rmse:283202.40225
[10]	validation_0-rmse:283284.27178
[0]	validation_0-rmse:279786.37516
[1]	validation_0-rmse:280888.11384
[2]	validation_0-rmse:282582.71390
[3]	validation_0-rmse:284738.62102
[4]	validation_0-rmse:285463.10791
[5]	validation_0-rmse:284763.74493
[6]	validation_0-rmse:287194.49483
[7]	validation_0-rmse:289254.20446
[8]	validation_0-rmse:290723.90314
[9]	validation_0-rmse:291644.78383
[10]	validation_0-rmse:293367.99959
[0]	validation_0-rmse:280846.67614
[1]	validation_0-rmse:282572.83243
[2]	validation_0-rmse:284730.53074
[3]	validation_0-rmse:285210.10863
[4]	validation_0-rmse:285267.76861
[5]	validation_0-rmse:283971.89166
[6]	validation_0-rmse:286819.45484
[7]	validation_0-rmse:287333.58466
[8]	validation_0-rmse:288069.96894
[9]	validation_0-rmse:288490.27684
[0]	validation_0-rmse:279576.51358
[1]	validation_0-rmse:280735.24054
[2]	validation_0-rmse:281899.79718
[3]	validation_0-rmse:282130.83978
[4]	validation_0-rmse:282451.63917
[5]	validation_0-rmse:282787.73086
[6]	validation_0-rmse:282235.20961
[7]	validation_0-rmse:283141.42701
[8]	validation_0-rmse:283454.04095
[9]	validation_0-rmse:283308.03487
[10]	validation_0-rmse:284518.01214
[0]	validation_0-rmse:301766.82468
[1]	validation_0-rmse:324158.08963
[2]	validation_0-rmse:331541.65100
[3]	validation_0-rmse:341526.02917
[4]	validation_0-rmse:349548.02143
[5]	validation_0-rmse:351292.05191
[6]	validation_0-rmse:356815.75944
[7]	validation_0-rmse:357528.05197
[8]	validation_0-rmse:359008.61018
[9]	validation_0-rmse:361305.59998
[10]	validation_0-rmse:360925.86108
[0]	validation_0-rmse:279141.06835
[1]	validation_0-rmse:279216.57152
[2]	validation_0-rmse:279405.68707
[3]	validation_0-rmse:279941.51633
[4]	validation_0-rmse:280479.78634
[5]	validation_0-rmse:281284.75798
[6]	validation_0-rmse:281813.31151

[7]	validation_0-rmse:282565.58688
[8]	validation_0-rmse:282839.09851
[9]	validation_0-rmse:282946.17028
[10]	validation_0-rmse:283377.92865
[0]	validation_0-rmse:297851.08288
[1]	validation_0-rmse:314863.66652
[2]	validation_0-rmse:322688.03861
[3]	validation_0-rmse:325715.13028
[4]	validation_0-rmse:335696.78013
[5]	validation_0-rmse:340002.37469
[6]	validation_0-rmse:344402.23731
[7]	validation_0-rmse:347495.52580
[8]	validation_0-rmse:350127.35497
[9]	validation_0-rmse:351435.19526
[0]	validation_0-rmse:278952.16156
[1]	validation_0-rmse:279093.20924
[2]	validation_0-rmse:279248.18220
[3]	validation_0-rmse:279477.03341
[4]	validation_0-rmse:279697.44790
[5]	validation_0-rmse:279790.20688
[6]	validation_0-rmse:279855.56295
[7]	validation_0-rmse:279999.21293
[8]	validation_0-rmse:280211.52123
[9]	validation_0-rmse:280407.81189
[0]	validation_0-rmse:278952.63316
[1]	validation_0-rmse:279094.24962
[2]	validation_0-rmse:279249.94629
[3]	validation_0-rmse:279480.33283
[4]	validation_0-rmse:279702.42941
[5]	validation_0-rmse:279795.85616
[6]	validation_0-rmse:279862.53535
[7]	validation_0-rmse:280007.11201
[8]	validation_0-rmse:280220.63187
[9]	validation_0-rmse:280418.38300
[10]	validation_0-rmse:280685.34438
[0]	validation_0-rmse:278946.09945
[1]	validation_0-rmse:279116.42929
[2]	validation_0-rmse:279370.92852
[3]	validation_0-rmse:279637.78277
[4]	validation_0-rmse:279859.37284
[5]	validation_0-rmse:279940.67024
[6]	validation_0-rmse:280199.27788
[7]	validation_0-rmse:280272.53251
[8]	validation_0-rmse:280500.12174
[9]	validation_0-rmse:280744.91645
[10]	validation_0-rmse:280718.62146
[0]	validation_0-rmse:278954.96270
[1]	validation_0-rmse:279085.20275
[2]	validation_0-rmse:279228.24557
[3]	validation_0-rmse:279441.63104
[4]	validation_0-rmse:279647.77995
[5]	validation_0-rmse:279880.16081
[6]	validation_0-rmse:279942.60639
[7]	validation_0-rmse:280076.17920
[8]	validation_0-rmse:280288.13846
[9]	validation_0-rmse:280373.89722
[0]	validation_0-rmse:279339.36194
[1]	validation_0-rmse:279675.68937
[2]	validation_0-rmse:279874.23479
[3]	validation_0-rmse:280109.56545
[4]	validation_0-rmse:280163.16077
[5]	validation_0-rmse:280692.53620
[6]	validation_0-rmse:281009.60908
[7]	validation_0-rmse:280982.84579
[8]	validation_0-rmse:281299.92726
[9]	validation_0-rmse:281307.27627

[10]	validation_0-rmse:281370.29539
[0]	validation_0-rmse:278973.99546
[1]	validation_0-rmse:279049.56903
[2]	validation_0-rmse:279138.58903
[3]	validation_0-rmse:279254.19986
[4]	validation_0-rmse:279354.07650
[5]	validation_0-rmse:279486.81897
[6]	validation_0-rmse:279612.94913
[7]	validation_0-rmse:279746.78777
[8]	validation_0-rmse:279910.11033
[9]	validation_0-rmse:279919.80488
[0]	validation_0-rmse:278940.62695
[1]	validation_0-rmse:279275.68037
[2]	validation_0-rmse:279267.59011
[3]	validation_0-rmse:279695.46381
[4]	validation_0-rmse:280225.18467
[5]	validation_0-rmse:280349.80269
[6]	validation_0-rmse:280258.10358
[7]	validation_0-rmse:280244.90916
[8]	validation_0-rmse:280543.93269
[9]	validation_0-rmse:280405.59694
[10]	validation_0-rmse:280708.21861
[0]	validation_0-rmse:279579.10536
[1]	validation_0-rmse:279920.23006
[2]	validation_0-rmse:280272.49690
[3]	validation_0-rmse:280737.34588
[4]	validation_0-rmse:281055.36133
[5]	validation_0-rmse:281124.86060
[6]	validation_0-rmse:280876.03420
[7]	validation_0-rmse:281076.06577
[8]	validation_0-rmse:281291.11727
[9]	validation_0-rmse:281342.11573
[10]	validation_0-rmse:281791.95463
[0]	validation_0-rmse:279849.92108
[1]	validation_0-rmse:280708.64480
[2]	validation_0-rmse:280985.49961
[3]	validation_0-rmse:283564.86998
[4]	validation_0-rmse:282624.47616
[5]	validation_0-rmse:283513.61992
[6]	validation_0-rmse:283974.23044
[7]	validation_0-rmse:284089.74421
[8]	validation_0-rmse:286738.65040
[9]	validation_0-rmse:286992.49657
[0]	validation_0-rmse:282238.73048
[1]	validation_0-rmse:285547.12124
[2]	validation_0-rmse:286409.18038
[3]	validation_0-rmse:287749.31085
[4]	validation_0-rmse:288795.02051
[5]	validation_0-rmse:290700.69854
[6]	validation_0-rmse:291661.90582
[7]	validation_0-rmse:292302.16629
[8]	validation_0-rmse:292393.49607
[9]	validation_0-rmse:295073.87341
[10]	validation_0-rmse:296015.32736
[0]	validation_0-rmse:278971.60777
[1]	validation_0-rmse:279287.41992
[2]	validation_0-rmse:279272.77512
[3]	validation_0-rmse:279674.13165
[4]	validation_0-rmse:279719.67757
[5]	validation_0-rmse:279632.25845
[6]	validation_0-rmse:279779.27134
[7]	validation_0-rmse:280031.98481
[8]	validation_0-rmse:280287.55295
[9]	validation_0-rmse:280138.69820
[0]	validation_0-rmse:279326.16077
[1]	validation_0-rmse:279538.26087

[2]	validation_0-rmse:279782.94238
[3]	validation_0-rmse:279945.44056
[4]	validation_0-rmse:280099.77267
[5]	validation_0-rmse:280311.15378
[6]	validation_0-rmse:280771.34757
[7]	validation_0-rmse:280640.31886
[8]	validation_0-rmse:280709.40939
[9]	validation_0-rmse:280803.53432
[10]	validation_0-rmse:280849.50648
[0]	validation_0-rmse:278972.29695
[1]	validation_0-rmse:279240.04173
[2]	validation_0-rmse:279797.12260
[3]	validation_0-rmse:280333.28163
[4]	validation_0-rmse:280623.89951
[5]	validation_0-rmse:280628.23763
[6]	validation_0-rmse:280074.22156
[7]	validation_0-rmse:279872.11633
[8]	validation_0-rmse:279846.13783
[9]	validation_0-rmse:280264.19695
[10]	validation_0-rmse:280631.98729
[0]	validation_0-rmse:279718.53034
[1]	validation_0-rmse:280984.92387
[2]	validation_0-rmse:281121.25565
[3]	validation_0-rmse:283330.79393
[4]	validation_0-rmse:282755.21025
[5]	validation_0-rmse:283523.85794
[6]	validation_0-rmse:283986.80507
[7]	validation_0-rmse:285334.18536
[8]	validation_0-rmse:285663.97229
[9]	validation_0-rmse:288089.62642
[0]	validation_0-rmse:281060.34469
[1]	validation_0-rmse:283867.25022
[2]	validation_0-rmse:285351.97763
[3]	validation_0-rmse:286411.92145
[4]	validation_0-rmse:286943.32921
[5]	validation_0-rmse:288169.09481
[6]	validation_0-rmse:290735.68835
[7]	validation_0-rmse:292251.50761
[8]	validation_0-rmse:292040.72301
[9]	validation_0-rmse:292056.93391
[0]	validation_0-rmse:279137.26852
[1]	validation_0-rmse:279510.22244
[2]	validation_0-rmse:279922.72894
[3]	validation_0-rmse:280605.14465
[4]	validation_0-rmse:281334.02234
[5]	validation_0-rmse:282039.37925
[6]	validation_0-rmse:282430.72928
[7]	validation_0-rmse:282533.29723
[8]	validation_0-rmse:282784.17691
[9]	validation_0-rmse:283191.88844
[10]	validation_0-rmse:283771.93299
[0]	validation_0-rmse:278947.22688
[1]	validation_0-rmse:279384.01246
[2]	validation_0-rmse:279705.98345
[3]	validation_0-rmse:280088.30316
[4]	validation_0-rmse:280049.09216
[5]	validation_0-rmse:280275.49438
[6]	validation_0-rmse:280322.40643
[7]	validation_0-rmse:280498.28814
[8]	validation_0-rmse:281041.35594
[9]	validation_0-rmse:281365.16835
[10]	validation_0-rmse:281145.27084
[0]	validation_0-rmse:294207.80643
[1]	validation_0-rmse:293710.23741
[2]	validation_0-rmse:295612.43229
[3]	validation_0-rmse:300674.15953

[4]	validation_0-rmse:304311.98889
[5]	validation_0-rmse:303256.63884
[6]	validation_0-rmse:304302.42907
[7]	validation_0-rmse:308332.01066
[8]	validation_0-rmse:312087.57315
[9]	validation_0-rmse:318082.46481
[10]	validation_0-rmse:322111.75138
[0]	validation_0-rmse:280020.37258
[1]	validation_0-rmse:281742.12238
[2]	validation_0-rmse:282681.38761
[3]	validation_0-rmse:282674.84681
[4]	validation_0-rmse:282649.12288
[5]	validation_0-rmse:282150.42573
[6]	validation_0-rmse:282822.68009
[7]	validation_0-rmse:283590.04829
[8]	validation_0-rmse:284085.56307
[9]	validation_0-rmse:286016.52739
[0]	validation_0-rmse:278954.27381
[1]	validation_0-rmse:279110.31798
[2]	validation_0-rmse:279282.71659
[3]	validation_0-rmse:279538.88748
[4]	validation_0-rmse:279786.79467
[5]	validation_0-rmse:279890.61666
[6]	validation_0-rmse:280062.55341
[7]	validation_0-rmse:280111.10645
[8]	validation_0-rmse:280129.83461
[9]	validation_0-rmse:280275.28420
[10]	validation_0-rmse:280743.26034
[0]	validation_0-rmse:279170.70431
[1]	validation_0-rmse:279801.29048
[2]	validation_0-rmse:279765.78402
[3]	validation_0-rmse:280584.81798
[4]	validation_0-rmse:280843.37467
[5]	validation_0-rmse:281167.22444
[6]	validation_0-rmse:280933.36528
[7]	validation_0-rmse:281660.64663
[8]	validation_0-rmse:282633.48664
[9]	validation_0-rmse:283122.00615
[10]	validation_0-rmse:283578.42392
[0]	validation_0-rmse:280423.29170
[1]	validation_0-rmse:281019.43789
[2]	validation_0-rmse:281134.43816
[3]	validation_0-rmse:280625.63516
[4]	validation_0-rmse:281331.53209
[5]	validation_0-rmse:281429.53687
[6]	validation_0-rmse:281484.30901
[7]	validation_0-rmse:281445.06801
[8]	validation_0-rmse:281555.42707
[9]	validation_0-rmse:282283.16694
[10]	validation_0-rmse:282681.33367
[0]	validation_0-rmse:279026.18411
[1]	validation_0-rmse:279148.01813
[2]	validation_0-rmse:279303.50610
[3]	validation_0-rmse:279436.71414
[4]	validation_0-rmse:279889.04396
[5]	validation_0-rmse:280104.10795
[6]	validation_0-rmse:280311.66574
[7]	validation_0-rmse:280356.54382
[8]	validation_0-rmse:280828.84202
[9]	validation_0-rmse:281134.60774
[0]	validation_0-rmse:279195.06022
[1]	validation_0-rmse:279656.99868
[2]	validation_0-rmse:280168.75705
[3]	validation_0-rmse:280719.31713
[4]	validation_0-rmse:281351.88569
[5]	validation_0-rmse:282011.69684

[6]	validation_0-rmse:282098.18000
[7]	validation_0-rmse:282567.69298
[8]	validation_0-rmse:283034.14335
[9]	validation_0-rmse:283420.57714
[10]	validation_0-rmse:283873.92229
[0]	validation_0-rmse:279045.16424
[1]	validation_0-rmse:279504.00590
[2]	validation_0-rmse:280012.14577
[3]	validation_0-rmse:280362.04391
[4]	validation_0-rmse:280566.79578
[5]	validation_0-rmse:280274.93750
[6]	validation_0-rmse:280576.47959
[7]	validation_0-rmse:280700.52919
[8]	validation_0-rmse:280745.57947
[9]	validation_0-rmse:280806.37256
[10]	validation_0-rmse:281095.58103
[0]	validation_0-rmse:280069.50773
[1]	validation_0-rmse:280696.42881
[2]	validation_0-rmse:282655.77666
[3]	validation_0-rmse:284034.39371
[4]	validation_0-rmse:284935.16307
[5]	validation_0-rmse:285703.59238
[6]	validation_0-rmse:287077.87960
[7]	validation_0-rmse:288498.18592
[8]	validation_0-rmse:289648.45568
[9]	validation_0-rmse:290986.52010
[0]	validation_0-rmse:279091.11459
[1]	validation_0-rmse:279724.96783
[2]	validation_0-rmse:280749.88467
[3]	validation_0-rmse:280801.58039
[4]	validation_0-rmse:281010.72671
[5]	validation_0-rmse:280824.08448
[6]	validation_0-rmse:280564.13561
[7]	validation_0-rmse:281208.73426
[8]	validation_0-rmse:281298.13134
[9]	validation_0-rmse:281528.56399
[0]	validation_0-rmse:279029.18181
[1]	validation_0-rmse:279531.78237
[2]	validation_0-rmse:279783.14913
[3]	validation_0-rmse:280506.50018
[4]	validation_0-rmse:281176.85040
[5]	validation_0-rmse:281939.59453
[6]	validation_0-rmse:282498.74601
[7]	validation_0-rmse:282651.32757
[8]	validation_0-rmse:282968.52360
[9]	validation_0-rmse:283091.89192
[0]	validation_0-rmse:278997.80780
[1]	validation_0-rmse:279013.21329
[2]	validation_0-rmse:279064.64715
[3]	validation_0-rmse:279219.77138
[4]	validation_0-rmse:279264.80365
[5]	validation_0-rmse:279414.14118
[6]	validation_0-rmse:279560.30561
[7]	validation_0-rmse:279724.98044
[8]	validation_0-rmse:279824.91750
[9]	validation_0-rmse:279760.29230
[0]	validation_0-rmse:280705.10799
[1]	validation_0-rmse:282576.94856
[2]	validation_0-rmse:284142.63044
[3]	validation_0-rmse:285021.60417
[4]	validation_0-rmse:285665.30683
[5]	validation_0-rmse:287781.40027
[6]	validation_0-rmse:288324.04492
[7]	validation_0-rmse:288563.85809
[8]	validation_0-rmse:288822.47758
[9]	validation_0-rmse:289736.05301

[10]	validation_0-rmse:290545.43417
100%|█████████████████████████████████████████████████████| 50/50 [00:13<00:00,  3.72trial/s, best loss: 278940.6270832908]

In [43]:
mlflow.autolog()

with mlflow.start_run(run_name="XGB Regressor autolog"):
    mlflow.set_tag("developer", "Praveen")
    mlflow.log_param("algorithm", "XGB Regressor with Autolog Params")
    mlflow.log_param("data", "/workspaces/mlops_sample/cleaned_data.csv")
    autolog_model = xgb.XGBRegressor(n_estimators = 810, learning_rate = 0.11014099849219953, max_depth = 4, reg_alpha = 0.9493672374210916, reg_lambda = 0.6839771610567229)
    autolog_model.fit(X_train, y_train)
    y_prediction = autolog_model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))
    mlflow.log_metric("rmse", rmse)

2026/05/26 10:50:51 WARNING mlflow.utils.autologging_utils: MLflow sklearn autologging is known to be compatible with 1.3.0 <= scikit-learn <= 1.7.0, but the installed version is 1.0.2. If you encounter errors during autologging, try upgrading / downgrading scikit-learn to a compatible version, or try upgrading MLflow.
2026/05/26 10:50:52 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2026/05/26 10:50:52 WARNING mlflow.utils.autologging_utils: MLflow statsmodels autologging is known to be compatible with 0.14.1 <= statsmodels <= 0.14.4, but the installed version is 0.13.2. If you encounter errors during autologging, try upgrading / downgrading statsmodels to a compatible version, or try upgrading MLflow.
2026/05/26 10:50:52 INFO mlflow.tracking.fluent: Autologging successfully enabled for statsmodels.
2026/05/26 10:50:52 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
2026/05/26 10:50:53 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/26 10:50:53 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/codespace/anaconda3/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [10:50:53] WARNING: /workspace/src/c_api/c_api.cc:1374: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats."
2026/05/26 10:51:02 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpu9uxtz5u/model, flavor: xgboost). Fall back to return ['xgboost==2.1.4']. Set logging level to DEBUG to see the full traceback.