In [1]:
#Importing Libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
!pip install mlflow

Requirement already satisfied: mlflow in /home/codespace/anaconda3/lib/python3.9/site-packages (3.1.4)
Requirement already satisfied: scipy<2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.7.3)
Requirement already satisfied: Flask<4 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.1.2)
Requirement already satisfied: gunicorn<24 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (23.0.0)
Requirement already satisfied: pyarrow<21,>=4.0.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (20.0.0)
Requirement already satisfied: scikit-learn<2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.0.2)
Requirement already satisfied: alembic!=1.10.0,<2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.16.5)
Requirement already satisfied: pandas<3 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.4.2)
Requirement already satisfied: matplotlib<4 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (3.5.1)
Requirement already satisfied: graphene<4 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (3.4.3)
Requirement already satisfied: mlflow-skinny==3.1.4 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (3.1.4)
Requirement already satisfied: numpy<3 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.21.5)
Requirement already satisfied: docker<8,>=4.0.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (7.1.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.4.32)
Requirement already satisfied: cachetools<7,>=5.0.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (6.2.6)
Requirement already satisfied: cloudpickle<4 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (2.0.0)
Requirement already satisfied: gitpython<4,>=3.1.9 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (3.1.50)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (0.39.0)
Requirement already satisfied: click<9,>=7.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (8.0.4)
Requirement already satisfied: packaging<26 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (21.3)
Requirement already satisfied: requests<3,>=2.17.3 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (2.32.5)
Requirement already satisfied: fastapi<1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (0.128.8)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (1.41.1)
Requirement already satisfied: pyyaml<7,>=5.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (6.0)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (0.102.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (1.41.1)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (0.5.5)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (8.7.1)
Requirement already satisfied: protobuf<7,>=3.12.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (6.33.6)
Requirement already satisfied: pydantic<3,>=1.10.8 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (2.13.4)
Requirement already satisfied: Mako in /home/codespace/anaconda3/lib/python3.9/site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.12)
Requirement already satisfied: tomli in /home/codespace/anaconda3/lib/python3.9/site-packages (from alembic!=1.10.0,<2->mlflow) (1.2.2)
Requirement already satisfied: google-auth~=2.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.4->mlflow) (2.50.0)
Requirement already satisfied: urllib3>=1.26.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from docker<8,>=4.0.0->mlflow) (1.26.9)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from fastapi<1->mlflow-skinny==3.1.4->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from fastapi<1->mlflow-skinny==3.1.4->mlflow) (0.0.4)
Requirement already satisfied: starlette<1.0.0,>=0.40.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from fastapi<1->mlflow-skinny==3.1.4->mlflow) (0.49.3)
Requirement already satisfied: itsdangerous>=0.24 in /home/codespace/anaconda3/lib/python3.9/site-packages (from Flask<4->mlflow) (2.0.1)
Requirement already satisfied: Werkzeug>=0.15 in /home/codespace/anaconda3/lib/python3.9/site-packages (from Flask<4->mlflow) (2.0.3)
Requirement already satisfied: Jinja2>=2.10.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from Flask<4->mlflow) (2.11.3)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.1.4->mlflow) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.1.4->mlflow) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.4->mlflow) (0.2.8)
Requirement already satisfied: cryptography>=38.0.3 in /home/codespace/anaconda3/lib/python3.9/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.4->mlflow) (48.0.0)
Requirement already satisfied: cffi>=2.0.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from cryptography>=38.0.3->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.4->mlflow) (2.0.0)
Requirement already satisfied: pycparser in /home/codespace/anaconda3/lib/python3.9/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.4->mlflow) (2.21)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from graphene<4->mlflow) (2.8.2)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from graphene<4->mlflow) (3.2.8)
Requirement already satisfied: zipp>=3.20 in /home/codespace/anaconda3/lib/python3.9/site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.1.4->mlflow) (3.23.1)
Requirement already satisfied: MarkupSafe>=0.23 in /home/codespace/anaconda3/lib/python3.9/site-packages (from Jinja2>=2.10.1->Flask<4->mlflow) (2.0.1)
Requirement already satisfied: pyparsing>=2.2.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from matplotlib<4->mlflow) (3.0.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from matplotlib<4->mlflow) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /home/codespace/anaconda3/lib/python3.9/site-packages (from matplotlib<4->mlflow) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from matplotlib<4->mlflow) (4.25.0)
Requirement already satisfied: pillow>=6.2.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from matplotlib<4->mlflow) (9.0.1)

Requirement already satisfied: opentelemetry-semantic-conventions==0.62b1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.1.4->mlflow) (0.62b1)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from pandas<3->mlflow) (2021.3)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/codespace/anaconda3/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.4->mlflow) (0.4.8)
Requirement already satisfied: annotated-types>=0.6.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.1.4->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /home/codespace/anaconda3/lib/python3.9/site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.1.4->mlflow) (2.46.4)
Requirement already satisfied: six>=1.5 in /home/codespace/anaconda3/lib/python3.9/site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/anaconda3/lib/python3.9/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.4->mlflow) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/anaconda3/lib/python3.9/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.4->mlflow) (2021.10.8)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.4->mlflow) (2.0.4)
Requirement already satisfied: joblib>=0.11 in /home/codespace/anaconda3/lib/python3.9/site-packages (from scikit-learn<2->mlflow) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from scikit-learn<2->mlflow) (2.2.0)
Requirement already satisfied: greenlet!=0.4.17 in /home/codespace/anaconda3/lib/python3.9/site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (1.1.1)
Requirement already satisfied: anyio<5,>=3.6.2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from starlette<1.0.0,>=0.40.0->fastapi<1->mlflow-skinny==3.1.4->mlflow) (4.12.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from anyio<5,>=3.6.2->starlette<1.0.0,>=0.40.0->fastapi<1->mlflow-skinny==3.1.4->mlflow) (1.3.1)
Requirement already satisfied: h11>=0.8 in /home/codespace/anaconda3/lib/python3.9/site-packages (from uvicorn<1->mlflow-skinny==3.1.4->mlflow) (0.16.0)

In [3]:
import mlflow

In [4]:
mlflow.set_tracking_uri("sqlite:///mlflow.db")

In [5]:
mlflow.set_experiment("HousePricePrediction")

2026/05/28 10:29:09 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/05/28 10:29:09 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.

<Experiment: artifact_location='/workspaces/mlops_sample/mlruns/1', creation_time=1779784903294, experiment_id='1', last_update_time=1779784903294, lifecycle_stage='active', name='HousePricePrediction', tags={'mlflow.sharedViewState.cd6101a9360b29aef84135a7315deede6de435fed32ccc466404e44adf9fede2': 'deflate;eJzFVE1v2zAM/SuFzsEQO07s5JZmbVcsGYakKwYUhStLdCJUljxJ7uIV+e+j7Hy47YZdBvQoiuQj3yP5TCxQwzaXQjowZEJIj2jDwZzXn6HGN3XOiKxyYD9YR41LnSjg5DS1jExyKi30SPN/478nZDqfo5MUObCaSTimnzInnnw8p45acPbwc3ffI4XmIG/BWKHVKULKs2WlLMZYkMAc8JmWVYGWyV23vIeVrgyDB3TsWhc+qX1t/djCe3MBaGZoM4VtoktqaIFvicwoodapoe7FR0G3KYfSbbpGlYJFbqjTpkFzdO1dPfoDweYM9nCxLaniwMnkmYwDHmYcYk7zYcQinsSjcAzjMMtyHg0GAZk4UyGrg3ycJzDijFEeZSzPaBLFwxBimgRR1h/t6d+1CF+FUj7/3R7xk+Ac1Ol9K6zIhBSuXtASy9h13TxVyPjl9XJ1kwb9dPntywo7YbrAJgFFmG1QYc/7M6kqgTAkiONxnCTJIBn0o3DztK23qvLd16VPdT5dkhZhpivlbvSszUUmQf/A/Ao1RcGvD+miKAz78SCKK54ok0PppwWVd76v/agJewUKvC78wFObrB3aDKVIhfMOmJnseq/qjcajfhgGoyjj65zxd6/XhKllGmFeVXpMbR/V8BHG6/evFHeE7O67Q7FHeTMWf0JTtLkOzU6e7RfPFyFsKWl9ABR2Cc196dT1zzr/St2PgLunYXRCX9XWQfG/4ZGTJwE/F3QrCvGr44oazYV1h008JpgylJwjc2/RKgtXRlcl8FsqK7DXx81rK9wIDhdF6eqX5rWPOcc+VCXl/tm9ObjstHJ6CbkBu7lQNJMnlddSZ1TOhYIm6UyrXKz9odpOt8K26iNvZXPWFawKrd1GgUX0/uk0f/fOi87AkN3uNxAGK0U='}>

In [5]:
data = pd.read_csv('House Price Prediction Dataset.csv')

In [6]:
data.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   object
 7   Condition  2000 non-null   object
 8   Garage     2000 non-null   object
 9   Price      2000 non-null   int64
dtypes: int64(7), object(3)
memory usage: 156.4+ KB

In [11]:
data.describe()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price
count,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000
mean,1000.500000,2786.209500,3.003500,2.55250,1.993500,1961.446000,537676.855000
std,577.494589,1295.146799,1.424606,1.10899,0.809188,35.926695,276428.845719
min,1.000000,501.000000,1.000000,1.00000,1.000000,1900.000000,50005.000000
25%,500.750000,1653.000000,2.000000,2.00000,1.000000,1930.000000,300098.000000
50%,1000.500000,2833.000000,3.000000,3.00000,2.000000,1961.000000,539254.000000
75%,1500.250000,3887.500000,4.000000,4.00000,3.000000,1993.000000,780086.000000
max,2000.000000,4999.000000,5.000000,4.00000,3.000000,2023.000000,999656.000000

In [12]:
data['Location'].unique()

array(['Downtown', 'Suburban', 'Urban', 'Rural'], dtype=object)

In [13]:
data['Condition'].unique()

array(['Excellent', 'Good', 'Fair', 'Poor'], dtype=object)

In [14]:
data['Garage'].unique()

array(['No', 'Yes'], dtype=object)

In [7]:
final_df  = pd.get_dummies(data = data,drop_first=True, columns=['Location', 'Condition', 'Garage'], dtype='int')

In [16]:
final_df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price,Location_Rural,Location_Suburban,Location_Urban,Condition_Fair,Condition_Good,Condition_Poor,Garage_Yes
0,1,1360,5,4,3,1970,149919,0,0,0,0,0,0,0
1,2,4272,5,4,3,1958,424998,0,0,0,0,0,0,0
2,3,3592,2,2,3,1938,266746,0,0,0,0,1,0,0
3,4,966,4,2,2,1902,244020,0,1,0,1,0,0,1
4,5,4926,1,4,2,1975,636056,0,0,0,1,0,0,1

In [17]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score

In [18]:
features = final_df[final_df.columns.drop(['Id','Price', 'YearBuilt'])].values

In [19]:
target = final_df['Price'].values

In [20]:
features

array([[1360,    5,    4, ...,    0,    0,    0],
       [4272,    5,    4, ...,    0,    0,    0],
       [3592,    2,    2, ...,    1,    0,    0],
       ...,
       [1062,    5,    1, ...,    0,    1,    0],
       [4062,    3,    1, ...,    0,    0,    1],
       [2989,    5,    1, ...,    0,    0,    0]])

In [21]:
target

array([149919, 424998, 266746, ..., 476925, 161119, 482525])

In [22]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.20, random_state=42)

In [23]:
training_data_path = final_df.to_csv('cleaned_data.csv')

# Running Different Models

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [25]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [26]:
##  Multiple Linear Regression

In [27]:
# with mlflow.start_run():
#     mlflow.set_tag("developer", "Praveen")
#     mlflow.log_param("data", "/workspaces/mlops_sample/cleaned_data.csv")
#     linear_reg = LinearRegression()
#     linear_reg.fit(X_train, y_train)
#     y_prediction = linear_reg.predict(X_test)
#     rmse = np.sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))
#     r2_score = r2_score(y_true=y_test, y_pred=y_prediction)
#     mlflow.log_metric("rmse", rmse)
#     mlflow.log_metric("r2_score", r2_score)

In [28]:
# with mlflow.start_run(run_name="Polynomial Regression"):
#     mlflow.set_tag("developer", "Praveen")
#     mlflow.log_param("data", "/workspaces/mlops_sample/cleaned_data.csv")
#     mlflow.log_param("algorithm", "Polynomial Function")
#     mlflow.log_param("polynomial_degree", "4")
#     poly = PolynomialFeatures(degree=4, include_bias=False)
#     X_poly = poly.fit_transform(X_train)
#     model = LinearRegression()
#     model.fit(X_poly, y_train)
#     y_prediction = model.predict(poly.fit_transform(X_test))
#     rmse = np.sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))
#     mlflow.log_metric("rmse", rmse)

In [29]:
!pip install xgboost

Requirement already satisfied: xgboost in /home/codespace/anaconda3/lib/python3.9/site-packages (2.1.4)
Requirement already satisfied: nvidia-nccl-cu12 in /home/codespace/anaconda3/lib/python3.9/site-packages (from xgboost) (2.30.4)
Requirement already satisfied: numpy in /home/codespace/anaconda3/lib/python3.9/site-packages (from xgboost) (1.21.5)
Requirement already satisfied: scipy in /home/codespace/anaconda3/lib/python3.9/site-packages (from xgboost) (1.7.3)

In [30]:
from xgboost import XGBRegressor

In [31]:
xgb = XGBRegressor()

In [32]:
# with mlflow.start_run(run_name="XGB Regressor default"):
#     mlflow.set_tag("developer", "Praveen")
#     mlflow.log_param("algorithm", "XGB Regressor with default Params")
#     mlflow.log_param("data", "/workspaces/mlops_sample/cleaned_data.csv")
#     xgb.fit(X_train, y_train)
#     y_prediction = xgb.predict(X_test)
#     rmse = np.sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))
#     mlflow.log_metric("rmse", rmse)

In [33]:
# !pip install hyperopt

In [34]:
# from hyperopt import fmin, tpe, hp, STATUS_OK, Trials

In [35]:
# k = 5
# print(f'thenumber is {k}')

In [36]:
import xgboost as xgb

In [37]:
# # 1. Define the search space
# space = {
#     'max_depth': hp.quniform('max_depth', 3, 10, 1),
#     'learning_rate': hp.loguniform('learning_rate', -3, 0),
#     'n_estimators': hp.quniform('n_estimators', 100, 1000, 10),
#     'reg_alpha': hp.uniform('reg_alpha', 0, 1),
#     'reg_lambda': hp.uniform('reg_lambda', 0, 1)
# }


# # 2. Define the objective function

# def objective(params):
#     # Convert parameters to correct types (Hyperopt often returns floats)
#     params['max_depth'] = int(params['max_depth'])
#     params['n_estimators'] = int(params['n_estimators'])
    
#     with mlflow.start_run(nested=True):
#         mlflow.set_tag("model", "xgboost")
#         model = xgb.XGBRegressor(**params, early_stopping_rounds=10, random_state=42)
#         model.fit(X_train, y_train, eval_set=[(X_test, y_test)])
#         preds = model.predict(X_test)
#         rmse = mean_squared_error(y_test, preds, squared=False)
#         actual_trees = model.best_iteration if hasattr(model, 'best_iteration') else params['n_estimators']

# # Log to MLflow
#         mlflow.log_params(params)
#         mlflow.log_metric("rmse", rmse)
#         mlflow.log_metric("best_iteration", actual_trees)
        
#         return {'loss': rmse, 'status': STATUS_OK}


# with mlflow.start_run(run_name="XGB_Hyperopt_Optimization"):
#     best_params = fmin(fn = objective, space = space, algo = tpe.suggest, max_evals = 50, trials = Trials())
#     mlflow.log_params(best_params)

In [39]:
mlflow.autolog()

with mlflow.start_run(run_name="New XGB Regressor autolog"):
    mlflow.set_tag("developer", "Praveen")
    mlflow.log_param("algorithm", "New XGB Regressor with Autolog Params")
    mlflow.log_param("data", "/workspaces/mlops_sample/cleaned_data.csv")
    autolog_model = xgb.XGBRegressor(n_estimators = 810, learning_rate = 0.11014099849219953, max_depth = 4, reg_alpha = 0.9493672374210916, reg_lambda = 0.6839771610567229)
    autolog_model.fit(X_train, y_train)
    y_prediction = autolog_model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))
    mlflow.log_metric("rmse", rmse)
    mlflow.log_artifact(local_path="/workspaces/mlops_sample/models", artifact_path="models/")

2026/05/27 09:48:03 WARNING mlflow.utils.autologging_utils: MLflow sklearn autologging is known to be compatible with 1.3.0 <= scikit-learn <= 1.7.0, but the installed version is 1.0.2. If you encounter errors during autologging, try upgrading / downgrading scikit-learn to a compatible version, or try upgrading MLflow.
2026/05/27 09:48:04 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2026/05/27 09:48:04 WARNING mlflow.utils.autologging_utils: MLflow statsmodels autologging is known to be compatible with 0.14.1 <= statsmodels <= 0.14.4, but the installed version is 0.13.2. If you encounter errors during autologging, try upgrading / downgrading statsmodels to a compatible version, or try upgrading MLflow.
2026/05/27 09:48:08 INFO mlflow.tracking.fluent: Autologging successfully enabled for statsmodels.
2026/05/27 09:48:08 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
2026/05/27 09:48:10 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/27 09:48:10 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/codespace/anaconda3/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [09:48:10] WARNING: /workspace/src/c_api/c_api.cc:1374: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats."
2026/05/27 09:48:14 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp8fsxhq3p/model, flavor: xgboost). Fall back to return ['xgboost==2.1.4']. Set logging level to DEBUG to see the full traceback.

In [41]:
mlflow.autolog()

with mlflow.start_run(run_name="New XGB model"):
    mlflow.set_tag("developer", "Praveen")
    mlflow.log_param("algorithm", "New XGB Regressor with Autolog Params")
    best_params = {
        'n_estimators':810,
        'learning_rate':0.11014099849219953,
        'max_depth':4,
        'reg_alpha':0.9493672374210916,
        'reg_lambda':0.6839771610567229    
    }
    
    
    mlflow.log_params(best_params)
    mlflow.log_param("data", "/workspaces/mlops_sample/cleaned_data.csv")
    autolog_model = xgb.XGBRegressor(n_estimators = 810, learning_rate = 0.11014099849219953, max_depth = 4, reg_alpha = 0.9493672374210916, reg_lambda = 0.6839771610567229)
    autolog_model.fit(X_train, y_train)
    y_prediction = autolog_model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_true=y_test, y_pred=y_prediction))
    mlflow.log_metric("rmse", rmse)
    mlflow.xgboost.log_model(xgb_model=autolog_model, artifact_path="new_model")

2026/05/27 10:18:59 WARNING mlflow.utils.autologging_utils: MLflow sklearn autologging is known to be compatible with 1.3.0 <= scikit-learn <= 1.7.0, but the installed version is 1.0.2. If you encounter errors during autologging, try upgrading / downgrading scikit-learn to a compatible version, or try upgrading MLflow.
2026/05/27 10:18:59 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2026/05/27 10:18:59 WARNING mlflow.utils.autologging_utils: MLflow statsmodels autologging is known to be compatible with 0.14.1 <= statsmodels <= 0.14.4, but the installed version is 0.13.2. If you encounter errors during autologging, try upgrading / downgrading statsmodels to a compatible version, or try upgrading MLflow.
2026/05/27 10:18:59 INFO mlflow.tracking.fluent: Autologging successfully enabled for statsmodels.
2026/05/27 10:18:59 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
2026/05/27 10:18:59 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/27 10:19:00 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/codespace/anaconda3/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [10:19:00] WARNING: /workspace/src/c_api/c_api.cc:1374: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats."
2026/05/27 10:19:03 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp5dihue8m/model, flavor: xgboost). Fall back to return ['xgboost==2.1.4']. Set logging level to DEBUG to see the full traceback.
2026/05/27 10:19:03 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
/home/codespace/anaconda3/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [10:19:03] WARNING: /workspace/src/c_api/c_api.cc:1374: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  warnings.warn(smsg, UserWarning)
2026/05/27 10:19:06 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpndkmogew/model, flavor: xgboost). Fall back to return ['xgboost==2.1.4']. Set logging level to DEBUG to see the full traceback.
2026/05/27 10:19:06 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

In [43]:
run_id = "e5841658e52c49538a30613ef1f46e2f"
model_path = "new_model" # The default name used in log_model(model, "model")

# 2. Construct the URI
model_uri = f"runs:/{run_id}/{model_path}"

# 3. Load the model
# Use pyfunc for a generic python object or flavor-specific (e.g., mlflow.sklearn)
loaded_model = mlflow.pyfunc.load_model(model_uri)

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/5 [00:00<?, ?it/s]

In [45]:
X_test[[0]]

array([[633,   1,   4,   2,   0,   0,   1,   1,   0,   0,   0]])

In [46]:
y_test[0]

514764

In [47]:
# 4. Use for predictions
predictions = loaded_model.predict(X_test[[0]])

In [48]:
predictions

array([639061.9], dtype=float32)

In [57]:
mlflow.version.VERSION

'3.1.4'

In [8]:
###Registering the models in the mlflow registry

In [6]:
from mlflow.tracking import MlflowClient

In [9]:
MLFLOW_TRACKING_URI  = "sqlite:///mlflow.db"

In [10]:
client = MlflowClient(tracking_uri=MLFLOW_TRACKING_URI)

In [15]:
experiments = client.search_experiments()

for exp in experiments:
    print(f"Name: {exp.name}, ID: {exp.experiment_id}, Location: {exp.artifact_location}")

Name: HousePricePrediction, ID: 1, Location: /workspaces/mlops_sample/mlruns/1
Name: Default, ID: 0, Location: mlflow-artifacts:/0

In [16]:
client.search_runs(experiment_ids=['1'], filter_string = "metrics.rmse > 332014.00", run_view_type=1, max_results=5)

[<Run: data=<RunData: metrics={'rmse': 332014.73664794414}, params={'algorithm': 'New XGB Regressor with Autolog Params',
  'base_score': 'None',
  'booster': 'None',
  'colsample_bylevel': 'None',
  'colsample_bynode': 'None',
  'colsample_bytree': 'None',
  'custom_metric': 'None',
  'data': '/workspaces/mlops_sample/cleaned_data.csv',
  'device': 'None',
  'early_stopping_rounds': 'None',
  'eval_metric': 'None',
  'gamma': 'None',
  'grow_policy': 'None',
  'interaction_constraints': 'None',
  'learning_rate': '0.11014099849219953',
  'max_bin': 'None',
  'max_cat_threshold': 'None',
  'max_cat_to_onehot': 'None',
  'max_delta_step': 'None',
  'max_depth': '4',
  'max_leaves': 'None',
  'maximize': 'None',
  'min_child_weight': 'None',
  'monotone_constraints': 'None',
  'multi_strategy': 'None',
  'n_estimators': '810',
  'n_jobs': 'None',
  'num_boost_round': '810',
  'num_parallel_tree': 'None',
  'objective': 'reg:squarederror',
  'random_state': 'None',
  'reg_alpha': '0.9493672374210916',
  'reg_lambda': '0.6839771610567229',
  'sampling_method': 'None',
  'scale_pos_weight': 'None',
  'subsample': 'None',
  'tree_method': 'None',
  'validate_parameters': 'None',
  'verbose_eval': 'True',
  'verbosity': 'None'}, tags={'developer': 'Praveen',
  'mlflow.runName': 'New XGB model',
  'mlflow.source.name': '/home/codespace/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py',
  'mlflow.source.type': 'LOCAL',
  'mlflow.user': 'codespace'}>, info=<RunInfo: artifact_uri='/workspaces/mlops_sample/mlruns/1/e5841658e52c49538a30613ef1f46e2f/artifacts', end_time=1779877146985, experiment_id='1', lifecycle_stage='active', run_id='e5841658e52c49538a30613ef1f46e2f', run_name='New XGB model', start_time=1779877139528, status='FINISHED', user_id='codespace'>, inputs=<RunInputs: dataset_inputs=[<DatasetInput: dataset=<Dataset: digest='d5d3c8f9', name='dataset', profile=('{"features_shape": [1600, 11], "features_size": 17600, "features_nbytes": '
  '70400}'), schema=('{"mlflow_tensorspec": {"features": "[{\\"type\\": \\"tensor\\", '
  '\\"tensor-spec\\": {\\"dtype\\": \\"float32\\", \\"shape\\": [-1, 11]}}]", '
  '"targets": null}}'), source=('{"tags": {"mlflow.user": "codespace", "mlflow.source.name": '
  '"/home/codespace/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", '
  '"mlflow.source.type": "LOCAL"}}'), source_type='code'>, tags=[<InputTag: key='mlflow.data.context', value='train'>]>,
  <DatasetInput: dataset=<Dataset: digest='8d8fd5a3', name='dataset', profile='{"features_shape": [400, 11], "features_size": 4400, "features_nbytes": 35200}', schema=('{"mlflow_tensorspec": {"features": "[{\\"type\\": \\"tensor\\", '
  '\\"tensor-spec\\": {\\"dtype\\": \\"int64\\", \\"shape\\": [-1, 11]}}]", '
  '"targets": null}}'), source=('{"tags": {"mlflow.user": "codespace", "mlflow.source.name": '
  '"/home/codespace/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", '
  '"mlflow.source.type": "LOCAL"}}'), source_type='code'>, tags=[<InputTag: key='mlflow.data.context', value='eval'>]>], model_inputs=[]>, outputs=None>,
 <Run: data=<RunData: metrics={'rmse': 332014.73664794414}, params={'algorithm': 'New XGB Regressor with Autolog Params',
  'base_score': 'None',
  'booster': 'None',
  'colsample_bylevel': 'None',
  'colsample_bynode': 'None',
  'colsample_bytree': 'None',
  'custom_metric': 'None',
  'data': '/workspaces/mlops_sample/cleaned_data.csv',
  'device': 'None',
  'early_stopping_rounds': 'None',
  'eval_metric': 'None',
  'gamma': 'None',
  'grow_policy': 'None',
  'interaction_constraints': 'None',
  'learning_rate': '0.11014099849219953',
  'max_bin': 'None',
  'max_cat_threshold': 'None',
  'max_cat_to_onehot': 'None',
  'max_delta_step': 'None',
  'max_depth': '4',
  'max_leaves': 'None',
  'maximize': 'None',
  'min_child_weight': 'None',
  'monotone_constraints': 'None',
  'multi_strategy': 'None',
  'n_jobs': 'None',
  'num_boost_round': '810',
  'num_parallel_tree': 'None',
  'objective': 'reg:squarederror',
  'random_state': 'None',
  'reg_alpha': '0.9493672374210916',
  'reg_lambda': '0.6839771610567229',
  'sampling_method': 'None',
  'scale_pos_weight': 'None',
  'subsample': 'None',
  'tree_method': 'None',
  'validate_parameters': 'None',
  'verbose_eval': 'True',
  'verbosity': 'None'}, tags={'developer': 'Praveen',
  'mlflow.runName': 'New XGB Regressor autolog',
  'mlflow.source.name': '/home/codespace/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py',
  'mlflow.source.type': 'LOCAL',
  'mlflow.user': 'codespace'}>, info=<RunInfo: artifact_uri='/workspaces/mlops_sample/mlruns/1/5a4d282a9f03496aacb49cb7a987e78a/artifacts', end_time=1779875294227, experiment_id='1', lifecycle_stage='active', run_id='5a4d282a9f03496aacb49cb7a987e78a', run_name='New XGB Regressor autolog', start_time=1779875288465, status='FINISHED', user_id='codespace'>, inputs=<RunInputs: dataset_inputs=[<DatasetInput: dataset=<Dataset: digest='d5d3c8f9', name='dataset', profile=('{"features_shape": [1600, 11], "features_size": 17600, "features_nbytes": '
  '70400}'), schema=('{"mlflow_tensorspec": {"features": "[{\\"type\\": \\"tensor\\", '
  '\\"tensor-spec\\": {\\"dtype\\": \\"float32\\", \\"shape\\": [-1, 11]}}]", '
  '"targets": null}}'), source=('{"tags": {"mlflow.user": "codespace", "mlflow.source.name": '
  '"/home/codespace/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", '
  '"mlflow.source.type": "LOCAL"}}'), source_type='code'>, tags=[<InputTag: key='mlflow.data.context', value='train'>]>,
  <DatasetInput: dataset=<Dataset: digest='8d8fd5a3', name='dataset', profile='{"features_shape": [400, 11], "features_size": 4400, "features_nbytes": 35200}', schema=('{"mlflow_tensorspec": {"features": "[{\\"type\\": \\"tensor\\", '
  '\\"tensor-spec\\": {\\"dtype\\": \\"int64\\", \\"shape\\": [-1, 11]}}]", '
  '"targets": null}}'), source=('{"tags": {"mlflow.user": "codespace", "mlflow.source.name": '
  '"/home/codespace/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", '
  '"mlflow.source.type": "LOCAL"}}'), source_type='code'>, tags=[<InputTag: key='mlflow.data.context', value='eval'>]>], model_inputs=[]>, outputs=None>,
 <Run: data=<RunData: metrics={'rmse': 332014.73664794414}, params={'algorithm': 'XGB Regressor with Autolog Params',
  'base_score': 'None',
  'booster': 'None',
  'colsample_bylevel': 'None',
  'colsample_bynode': 'None',
  'colsample_bytree': 'None',
  'custom_metric': 'None',
  'data': '/workspaces/mlops_sample/cleaned_data.csv',
  'device': 'None',
  'early_stopping_rounds': 'None',
  'eval_metric': 'None',
  'gamma': 'None',
  'grow_policy': 'None',
  'interaction_constraints': 'None',
  'learning_rate': '0.11014099849219953',
  'max_bin': 'None',
  'max_cat_threshold': 'None',
  'max_cat_to_onehot': 'None',
  'max_delta_step': 'None',
  'max_depth': '4',
  'max_leaves': 'None',
  'maximize': 'None',
  'min_child_weight': 'None',
  'monotone_constraints': 'None',
  'multi_strategy': 'None',
  'n_jobs': 'None',
  'num_boost_round': '810',
  'num_parallel_tree': 'None',
  'objective': 'reg:squarederror',
  'random_state': 'None',
  'reg_alpha': '0.9493672374210916',
  'reg_lambda': '0.6839771610567229',
  'sampling_method': 'None',
  'scale_pos_weight': 'None',
  'subsample': 'None',
  'tree_method': 'None',
  'validate_parameters': 'None',
  'verbose_eval': 'True',
  'verbosity': 'None'}, tags={'developer': 'Praveen',
  'mlflow.runName': 'XGB Regressor autolog',
  'mlflow.source.name': '/home/codespace/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py',
  'mlflow.source.type': 'LOCAL',
  'mlflow.user': 'codespace'}>, info=<RunInfo: artifact_uri='/workspaces/mlops_sample/mlruns/1/8c2dba0afb2f484c89649ea361d1d050/artifacts', end_time=1779792662700, experiment_id='1', lifecycle_stage='active', run_id='8c2dba0afb2f484c89649ea361d1d050', run_name='XGB Regressor autolog', start_time=1779792652113, status='FINISHED', user_id='codespace'>, inputs=<RunInputs: dataset_inputs=[<DatasetInput: dataset=<Dataset: digest='d5d3c8f9', name='dataset', profile=('{"features_shape": [1600, 11], "features_size": 17600, "features_nbytes": '
  '70400}'), schema=('{"mlflow_tensorspec": {"features": "[{\\"type\\": \\"tensor\\", '
  '\\"tensor-spec\\": {\\"dtype\\": \\"float32\\", \\"shape\\": [-1, 11]}}]", '
  '"targets": null}}'), source=('{"tags": {"mlflow.user": "codespace", "mlflow.source.name": '
  '"/home/codespace/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", '
  '"mlflow.source.type": "LOCAL"}}'), source_type='code'>, tags=[<InputTag: key='mlflow.data.context', value='train'>]>,
  <DatasetInput: dataset=<Dataset: digest='8d8fd5a3', name='dataset', profile='{"features_shape": [400, 11], "features_size": 4400, "features_nbytes": 35200}', schema=('{"mlflow_tensorspec": {"features": "[{\\"type\\": \\"tensor\\", '
  '\\"tensor-spec\\": {\\"dtype\\": \\"int64\\", \\"shape\\": [-1, 11]}}]", '
  '"targets": null}}'), source=('{"tags": {"mlflow.user": "codespace", "mlflow.source.name": '
  '"/home/codespace/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", '
  '"mlflow.source.type": "LOCAL"}}'), source_type='code'>, tags=[<InputTag: key='mlflow.data.context', value='eval'>]>], model_inputs=[]>, outputs=None>,
 <Run: data=<RunData: metrics={'rmse': 343852.88725505484}, params={'algorithm': 'Polynomial Function',
  'data': '/workspaces/mlops_sample/cleaned_data.csv',
  'polynomial_degree': '4'}, tags={'developer': 'Praveen',
  'mlflow.runName': 'Polynomial Regression',
  'mlflow.source.name': '/home/codespace/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py',
  'mlflow.source.type': 'LOCAL',
  'mlflow.user': 'codespace'}>, info=<RunInfo: artifact_uri='/workspaces/mlops_sample/mlruns/1/5d281cf76f624ab6af50479ecb0afe28/artifacts', end_time=1779784907895, experiment_id='1', lifecycle_stage='active', run_id='5d281cf76f624ab6af50479ecb0afe28', run_name='Polynomial Regression', start_time=1779784907238, status='FINISHED', user_id='codespace'>, inputs=<RunInputs: dataset_inputs=[], model_inputs=[]>, outputs=None>]

In [17]:
## Registering a model

In [31]:
# model_path = artifacts
XGB_MODEL_URI = "runs:/e5841658e52c49538a30613ef1f46e2f/model"

In [32]:
mlflow.register_model(model_uri = XGB_MODEL_URI, name="HousePrice-Predictor")

Registered model 'HousePrice-Predictor' already exists. Creating a new version of this model...
2026/05/28 11:15:02 WARNING mlflow.tracking._model_registry.fluent: Run with id e5841658e52c49538a30613ef1f46e2f has no artifacts at artifact path 'model', registering model based on models:/m-e4a47968500d4c3089c7a91458fe9434 instead
Created version '3' of model 'HousePrice-Predictor'.

<ModelVersion: aliases=[], creation_timestamp=1779966902987, current_stage='None', deployment_job_state=None, description=None, last_updated_timestamp=1779966902987, metrics=None, model_id=None, name='HousePrice-Predictor', params=None, run_id='e5841658e52c49538a30613ef1f46e2f', run_link=None, source='models:/m-e4a47968500d4c3089c7a91458fe9434', status='READY', status_message=None, tags={}, user_id=None, version=3>

In [30]:
import mlflow.xgboost

# Correct way to format the URI
model_uri = "runs:/e5841658e52c49538a30613ef1f46e2f/model" 
loaded_model = mlflow.xgboost.load_model(model_uri)

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/5 [00:00<?, ?it/s]

In [39]:
registered_models = mlflow.search_registered_models()
for model in registered_models:
    print(f"Model Name: {model.name}")

Model Name: HousePrice-Predictor

In [44]:
for versions in client.get_latest_versions(name = "HousePrice-Predictor"):
    print(f"version:{versions.version}, stage: {versions.current_stage}")

version:3, stage: None
version:2, stage: Staging

/tmp/ipykernel_8129/2968444727.py:1: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  for versions in client.get_latest_versions(name = "HousePrice-Predictor"):

In [47]:
client.transition_model_version_stage(name= 'HousePrice-Predictor', version=3, stage='Production')

/tmp/ipykernel_8129/139806900.py:1: FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  client.transition_model_version_stage(name= 'HousePrice-Predictor', version=3, stage='Production')

<ModelVersion: aliases=[], creation_timestamp=1779966902987, current_stage='Production', deployment_job_state=None, description='New XGB Model', last_updated_timestamp=1779969909691, metrics=None, model_id=None, name='HousePrice-Predictor', params=None, run_id='e5841658e52c49538a30613ef1f46e2f', run_link=None, source='models:/m-e4a47968500d4c3089c7a91458fe9434', status='READY', status_message=None, tags={'algorithm': 'new-xgb', 'rmse': '332014.73664794414'}, user_id=None, version=3>

In [48]:
## Checking the staged and production models performance

In [ ]:
version3_model_uri = "runs:/e5841658e52c49538a30613ef1f46e2f/model"
version2_model_uri = "runs:/e5841658e52c49538a30613ef1f46e2f/model"